### ISSUE TITLE
Can we upgrade binaries? some are 4 years old

### ISSUE THREAD

**Issue by caub** [imagemin/pngquant-bin#57] opened 2017-03-06 15:44 UTC

**Comment by shinnn** [comment] 2017-03-06 15:49
Duplicate of https://github.com/imagemin/pngquant-bin/issues/54

**Closed by shinnn** 2017-03-06 15:49 UTC

**Comment by caub** [comment] 2017-03-06 18:32
I don't see something that prevent the upgrades in those issues, or I'm missing some other fact?
