### ISSUE TITLE
Why version 2.4.1 (April 2015)?

### ISSUE THREAD

**Issue by drmrbrewer** [imagemin/pngquant-bin#59] opened 2017-03-13 13:48 UTC
When I install `pngquant-bin` on Ubuntu 14.04 with:

    $ npm install --save pngquant-bin

why do I get an old version of pngquant?

    $ pngquant --version
    2.4.1 (April 2015)

**Comment by shinnn** [comment] 2017-03-14 05:34
Duplicate of https://github.com/imagemin/pngquant-bin/issues/57

**Closed by shinnn** 2017-03-14 05:34 UTC

**Comment by drmrbrewer** [comment] 2017-03-14 08:33
Sorry, but it isn't helpful just to close the issue without comment, and merely link to other issues that offer no real insight and no workable solution.  

The workaround in one of the linked posts is to install pngquant separately and then override the binary link in `node_modules`... but this isn't at all useful because whilst it may work in the development environment, it isn't really to do this hack when deploying to a remote production environment (I'm thinking git pushing to heroku here).

Still confused as to why it's not possible simply to use newer binaries in the `pngquant-bin` package itself... it seems that pre-compiled binaries are [readily available](https://pkgs.org/download/pngquant)?
